In [103]:
import numpy as np

### The Basic

In [104]:
a = np.array([1,2,3])
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])

In [105]:
a.ndim , b.ndim

(1, 2)

In [106]:
a.shape, b.shape

((3,), (2, 3))

In [107]:
a.dtype, b.dtype

(dtype('int32'), dtype('float64'))

In [108]:
a.size, b.size

(3, 6)

In [109]:
a.itemsize, b.itemsize

(4, 8)

In [110]:
a.nbytes, b.nbytes

(12, 48)

In [111]:
a.itemsize * a.nbytes, b.itemsize* b.nbytes

(48, 384)

### Accesssing/ changing specigic elements, rows, columns, etc

In [112]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [113]:
# get a specific elenment [row, column]
a[1,5] # or a[1][5]

13

In [114]:
# get row 0 and all column
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [115]:
# get all rows and column 2
a[:,2]

array([ 3, 10])

In [116]:
# getting a little more fancy [start_index : end_index:stepsize] : row 0 from first element to fourth element, step by 2
a[0, 1:4:2]

array([2, 4])

In [117]:
# stick an index with a value : assign row 1 - column 5 with value 20
a[1,5] =20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [118]:
# assign all row at column 3 with value 1 in first row and value 2 in second row
a[:, 3] = [1,2] 
a

array([[ 1,  2,  3,  1,  5,  6,  7],
       [ 8,  9, 10,  2, 12, 20, 14]])

####  3d example

In [119]:
b =np.array([
    [
        [1,2],[3,4]
    ],
    [
        [5,6],[7,8]
    ]
])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [120]:
# get the specific element (work outside in): all rows (row-all columns)  3d-array[row, row, column]
b[:,1]

array([[3, 4],
       [7, 8]])

In [121]:
# replace all rows at (row 1 and all column) with value [9,9],[8,8]
b[:, 1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing diferent types of arrays

In [122]:
import numpy as np

In [123]:
# all 0s matrix
np.zeros(5) # array 1-d

array([0., 0., 0., 0., 0.])

In [124]:
np.zeros([2,4,2]) # array 3d

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [125]:
np.ones(2, dtype='int32')

array([1, 1])

In [126]:
# any orther number
np.full(2, 4) # 2d of number 4

array([4, 4])

In [3]:
import numpy as np
np.full((2,4), 2) # 2x4 of number 2

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [128]:
a, a.shape

(array([[ 1,  2,  3,  1,  5,  6,  7],
        [ 8,  9, 10,  2, 12, 20, 14]]),
 (2, 7))

In [129]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [130]:
# use full-like without shape of array
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [131]:
# random decimal numbers
np.random.rand(2,3) # array 2x3

array([[0.63721144, 0.99154654, 0.42539643],
       [0.02665591, 0.71526983, 0.48558405]])

In [132]:
# random int numbers random.randint(int, size)
np.random.randint(3, size=(3,3)) # array with shape (3,3) in range(3)

array([[0, 1, 0],
       [2, 2, 2],
       [0, 2, 1]])

In [133]:
np.random.randint(3,6, size=(3,4))

array([[5, 3, 3, 4],
       [3, 4, 5, 3],
       [3, 5, 4, 3]])

In [134]:
np.random.randint(-2, 3, size = (a.shape))

array([[ 0,  0, -2, -1, -1, -2,  0],
       [ 1,  1,  2, -1,  2,  1, -2]])

In [136]:
# The identity maxtrix
np.identity(3) # matrix with diagonal value 1, and shape (3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [152]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis =0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [153]:
r2 = np.repeat(arr, 3, axis =1)
r2

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [154]:
arr[0][1]

2

In [159]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
output[1:-1, 1:-1] = z
print(z)
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays !!!!

In [161]:
a  = np.array([1,2,3])
b  = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [165]:
a = ([0, 1,2])
b = a.copy()
b[0] = 100
print(a)
print(b)

[0, 1, 2]
[100, 1, 2]


## Mathematics

In [167]:
a = np.array([1,2,3,4])

In [168]:
a + 2

array([3, 4, 5, 6])

In [169]:
a * 2

array([2, 4, 6, 8])

In [170]:
a /3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [171]:
b = np.array([1,2,3,2])

In [173]:
print(a + b)
print(a-b)
print(a*b)
print(a/b)

[2 4 6 6]
[0 0 0 2]
[1 4 9 8]
[1. 1. 1. 2.]


In [175]:
# take the sin, cos
np.cos(a)
# see more in spicy document

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Linear Algebra

In [178]:
a = np.ones((2,3))
b = np.full((3,2), 2)
a, b

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[2, 2],
        [2, 2],
        [2, 2]]))

In [179]:
a.dot(b)

array([[6., 6.],
       [6., 6.]])

In [180]:
# or 
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [181]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [183]:
## Reference docs (spicy)
# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [187]:
stats = np.array([[1,2,3],[4,5,6]])
stats.mean(),stats.min(), stats.max(), stats.sum()

(3.5, 1, 6, 21)

In [193]:
np.max(stats, axis=0).sum()

15

### Reorganizing arrays

In [197]:
bf = np.array([[1,2,3],[4,5,6]])
af = bf.reshape((2,3))
af

array([[1, 2, 3],
       [4, 5, 6]])

In [201]:
# Stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2,v1,v2])) # vertical stack
print(np.hstack((v1,v2)))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


### Miscellanious

#### Load data from file

In [210]:
file_data = np.genfromtxt('numbers.txt', delimiter = ',')
file_data

array([[  1.,   2.,   3.,   4.,   5., 199.,  23.,   2.,   4.,   5.,   5.,
          5.,   5.,   2.,   2.,  23.,   2.,   3.,  13.,  13.,   1.,  23.,
        123.,   1.,  31.],
       [  1.,   2.,   3.,   4.,   5., 199.,  23.,   2.,   4.,   5.,   5.,
          5.,   5.,   2.,   2.,  23.,   2.,   3.,  13.,  13.,   1.,  23.,
        123.,   1.,  31.],
       [  1.,   2.,   3.,   4.,   5., 199.,  23.,   2.,   4.,   5.,   5.,
          5.,   5.,   2.,   2.,  23.,   2.,   3.,  13.,  13.,   1.,  23.,
        123.,   1.,  31.],
       [  1.,   2.,   3.,   4.,   5., 199.,  23.,   2.,   4.,   5.,   5.,
          5.,   5.,   2.,   2.,  23.,   2.,   3.,  13.,  13.,   1.,  23.,
        123.,   1.,  31.],
       [  1.,   2.,   3.,   4.,   5., 199.,  23.,   2.,   4.,   5.,   5.,
          5.,   5.,   2.,   2.,  23.,   2.,   3.,  13.,  13.,   1.,  23.,
        123.,   1.,  31.],
       [  1.,   2.,   3.,   4.,   5., 199.,  23.,   2.,   4.,   5.,   5.,
          5.,   5.,   2.,   2.,  23.,   2.,   3.,  

In [216]:
file_data = file_data.astype('int')
file_data

array([[  1,   2,   3,   4,   5, 199,  23,   2,   4,   5,   5,   5,   5,
          2,   2,  23,   2,   3,  13,  13,   1,  23, 123,   1,  31],
       [  1,   2,   3,   4,   5, 199,  23,   2,   4,   5,   5,   5,   5,
          2,   2,  23,   2,   3,  13,  13,   1,  23, 123,   1,  31],
       [  1,   2,   3,   4,   5, 199,  23,   2,   4,   5,   5,   5,   5,
          2,   2,  23,   2,   3,  13,  13,   1,  23, 123,   1,  31],
       [  1,   2,   3,   4,   5, 199,  23,   2,   4,   5,   5,   5,   5,
          2,   2,  23,   2,   3,  13,  13,   1,  23, 123,   1,  31],
       [  1,   2,   3,   4,   5, 199,  23,   2,   4,   5,   5,   5,   5,
          2,   2,  23,   2,   3,  13,  13,   1,  23, 123,   1,  31],
       [  1,   2,   3,   4,   5, 199,  23,   2,   4,   5,   5,   5,   5,
          2,   2,  23,   2,   3,  13,  13,   1,  23, 123,   1,  31]])

In [217]:
file_data.dtype

dtype('int32')

### Boolean and advanced indexing

In [218]:
file_data > 50

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False],


In [231]:
file_data[file_data > 50]

array([199, 123, 199, 123, 199, 123, 199, 123, 199, 123, 199, 123])

In [233]:
np.array(file_data >50)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False],
       [False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False],


In [237]:
np.any(file_data > 50), np.all(file_data > 50), np.any(file_data > 50, axis = 0)

(True,
 False,
 array([False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False]))

In [241]:
((file_data > 50) & (file_data < 100))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False],


In [242]:
(~(file_data > 50) & (file_data < 100))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True, False,  True,  True],


In [243]:
file_data[[0,1,2,3],[1,2,3,4]]

array([2, 3, 4, 5])